// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9p26zTKQpPKPvdQkka-Tz0J9QC-oc2Q',
    appId: '1:436823431645:web:19317966e754c851fabe34',
    messagingSenderId: '436823431645',
    projectId: 'agsm-21341',
    authDomain: 'agsm-21341.firebaseapp.com',
    databaseURL: 'https://agsm-21341-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agsm-21341.firebasestorage.app',
    measurementId: 'G-460DEJQ18P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL9IysJW0pfD2evrV04rQMWr4ALPtT2AA',
    appId: '1:436823431645:android:08164c3e22d54a37fabe34',
    messagingSenderId: '436823431645',
    projectId: 'agsm-21341',
    databaseURL: 'https://agsm-21341-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agsm-21341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVBy8wg3kw6r0fAFwsCj4475f1-TJgN3g',
    appId: '1:436823431645:ios:5672917aba7c4c58fabe34',
    messagingSenderId: '436823431645',
    projectId: 'agsm-21341',
    databaseURL: 'https://agsm-21341-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agsm-21341.firebasestorage.app',
    iosBundleId: 'com.example.nepro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVBy8wg3kw6r0fAFwsCj4475f1-TJgN3g',
    appId: '1:436823431645:ios:5672917aba7c4c58fabe34',
    messagingSenderId: '436823431645',
    projectId: 'agsm-21341',
    databaseURL: 'https://agsm-21341-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agsm-21341.firebasestorage.app',
    iosBundleId: 'com.example.nepro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk9p26zTKQpPKPvdQkka-Tz0J9QC-oc2Q',
    appId: '1:436823431645:web:8331f591543138d3fabe34',
    messagingSenderId: '436823431645',
    projectId: 'agsm-21341',
    authDomain: 'agsm-21341.firebaseapp.com',
    databaseURL: 'https://agsm-21341-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'agsm-21341.firebasestorage.app',
    measurementId: 'G-2DJZHVSYJB',
  );
}
